[pytest]
addopts = --browser chromium --browser firefox -s --screenshot=on --video=on -W ignore::DeprecationWarning -n auto --alluredir=allure-results --clean-alluredir --reruns 1 --reruns-delay 3
base_url = https://opensource-demo.orangehrmlive.com
testpaths = tests
bdd_features_base_dir = features/
markers =
    TC-01: Test Case 01
    TC-02: Test Case 02
    TC-03: Test Case 03
    TC-07: Test Case 07
    TC-04: Test Case 04
    TC-05: Test Case 05
    TC-06: Test Case 06
    TC-08: Test Case 08
    TC-10: Test Case 10
    TC-09: Test Case 09